name: Testing environment

on:
  workflow_dispatch:
    inputs:
      test_value:
        type: string
        description: Type a test number
      
  # Triggers the workflow every 2h 17minutes
  # schedule:
  #   - cron: "17 */12 * * *"

jobs:
  input-test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        
        - name: Test another thing
          run: |
            # Assign the local variable
            MY_VAR=my-value
    
            # Use the local variable
            echo "The value of MY_VAR is: $MY_VAR"

        - name: Test test_value
          run: |
                a="${{github.event.inputs.test_value}}"
                echo $a
                if [[ $a != "" ]]
                then
                    echo "$a"
                else
                    echo "null"
                fi
